### ISSUE TITLE
Responsibility clash of `CCEModel` with `CCEClient

### ISSUE THREAD

**Issue by arminWel** [hpi-swa-teaching/CollaborativeCodeEditing#19]
At the moment the `CCEModel` is almost a pivot for the whole Client-package. E.g. it distributes incoming request. That should probably be in the `CCEClient` as this is the point, where the requests arrive.
This could unclutter our architecture.

**Comment by simonstadlinger** [comment]
We have to discuss on this a little bit. Because with the architecture you are proposing, the client becomes the god class and has to have a reference to all our modules.

**Comment by arminWel** [comment]
Indeed we should do that. My reasoning is that there must be a pivot class. But it would be good if that'd be the sole responsibility of that class. Atm the model is responsible for the GUI and for that.
